name: security-action
on:
  push:
    branches: [veracode-actions] 
    
jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: checkout code
        uses: actions/checkout@v3
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
    
      - name: Build the App
        working-directory: ./app/
        run: dotnet publish -c Debug -p:UseAppHost=false

      - name: Zip Application Files 
        uses: vimtor/action-zip@v1
        with:
          files: app/bin/Debug/netcoreapp3.1/
          dest: verademodotnetcore.zip

      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: scan-target
          path: verademodotnetcore.zip

  veracode-sca:
    runs-on: ubuntu-latest
    name: veracode sca
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: veracode sca scan
        env: 
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan app --update-advisor --uri-as-name --ref ${{ github.ref_name }}

  veracode-container-iac-secrets-scan:
    runs-on: ubuntu-latest
    name: Veracode Container/IaC/Secrets scan
    needs: [ build ]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Veracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.3
        with:
          vid: '${{ secrets.VERACODE_ID }}'
          vkey: '${{ secrets.VERACODE_KEY }}'
          command: "scan" 
          type: "directory"
          source: "./"
          format: "table"
          debug: false
          fail_build: false

  veracode-sast-sandbox-scan:
    name: veracode sandbox branch scan
    runs-on: ubuntu-latest
    needs: [ build, veracode-sca, veracode-container-iac-secrets-scan ]
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3

      - name: get artifact
        uses: actions/download-artifact@v3
        with:
          name: scan-target

      - name: veracode sandbox branch scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'verademo-dotnetcore'
          createprofile: false
          filepath: 'verademodotnetcore.zip'
          vid: '${{ secrets.VERACODE_ID }}'
          vkey: '${{ secrets.VERACODE_KEY }}'
          createsandbox: 'true'
          sandboxname: "${{ github.ref }}"
          version: "${{ github.run_id }}"
          scantimeout: 0

  veracode-sast-policy-scan:
    name: veracode policy scan
    runs-on: ubuntu-latest
    needs: [ build, veracode-sca, veracode-container-iac-secrets-scan, veracode-sast-sandbox-scan ]
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        
      - name: get artifact
        uses: actions/download-artifact@v3
        with:
          name: scan-target
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'verademo-dotnetcore'
          createprofile: false
          filepath: 'verademodotnetcore.zip'
          vid: '${{ secrets.VERACODE_ID }}'
          vkey: '${{ secrets.VERACODE_KEY }}'
          version: "${{ github.run_id }}"
          scantimeout: 0

  veracode-sast-pipeline-scan:
    runs-on: ubuntu-latest
    needs: [ build, veracode-sca, veracode-container-iac-secrets-scan, veracode-sast-sandbox-scan ]
    name: veracode sast pipeline scan

    steps:
      - name: get artifact
        uses: actions/download-artifact@v3
        with:
          name: scan-target

      # debugging steps can be handy...
      - name: debug1
        run: |
          pwd
          ls -l

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.16
        with:
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_KEY }}
          file: "verademodotnetcore.zip"
          veracode_policy_name: "Veracode Recommended Medium"
          fail_build: "true"
