name: security-action
on:
  push:
    branches: [csharp-wrapper]
    
jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: checkout code
        uses: actions/checkout@v3
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
    
      - name: Build the App
        working-directory: ./app/
        run: dotnet publish -c Debug -p:UseAppHost=false

      - name: Zip Application Files 
        uses: vimtor/action-zip@v1
        with:
          files: app/bin/Debug/netcoreapp3.1/
          dest: verademodotnetcore.zip

      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: scan-target
          path: verademodotnetcore.zip


  veracode-sast-sandbox-scan:
    name: veracode sandbox branch scan
    runs-on: windows-2022
    needs: [ build ]
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3

      - name: get artifact
        uses: actions/download-artifact@v3
        with:
          name: scan-target

      - name: install powershell
        uses: Amadevus/pwsh-script@v2.0.3
                    
      - name: Veracode sandbox Scan
        env:
          VID: ${{ secrets.VERACODE_ID }} # Lembrar de criar as credenciais no Secrets
          VKEY: ${{ secrets.VERACODE_KEY }}
        run: |
          Invoke-WebRequest -Uri "https://tools.veracode.com/integrations/API-Wrappers/CSharp/bin/VeracodeCSharpAPI.zip" -OutFile "VeracodeCSharpAPI.zip"
          Expand-Archive -Path "VeracodeCSharpAPI.zip" -DestinationPath "$(Build.ArtifactStagingDirectory)"
          dir $(Build.ArtifactStagingDirectory)
          .\VeracodeC#API.exe -vid $VID -vkey $VKEY -action uploadandscan -appname 'verademo-dotnetcore' -createprofile true -filepath 'verademodotnetcore.zip' -version ${{ github.run_id }}
