name: security-action
on:
  push:
    branches: [auto-package] 
    
jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: checkout code
        uses: actions/checkout@v3
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
    
      - name: Build the App
        working-directory: ./app/
        run: |
            curl -fsS https://tools.veracode.com/veracode-cli/install | sh
            ./veracode package --source . --type directory --output verascan --trust --debug



